using System.Collections.Immutable;
using System.Security.Cryptography;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace HybridCPU.Compiler.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class StaticContractGenerator : IIncrementalGenerator
{
    private const string Marker = "HybridCPU.Compiler.Profiles.HybridCpuStaticContractAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol?> candidates = context.SyntaxProvider
            .CreateSyntaxProvider(static (node, _) => node is InterfaceDeclarationSyntax { AttributeLists.Count: > 0 },
                static (syntax, _) => syntax.SemanticModel.GetDeclaredSymbol((InterfaceDeclarationSyntax)syntax.Node) as INamedTypeSymbol)
            .Where(static symbol => symbol is not null);
        context.RegisterSourceOutput(candidates.Collect(), static (production, symbols) =>
        {
            var selected = new Dictionary<string, INamedTypeSymbol>(StringComparer.Ordinal);
            foreach (INamedTypeSymbol? candidate in symbols)
            {
                if (candidate is null || !IsMarked(candidate)) continue;
                selected[candidate.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)] = candidate;
            }
            foreach (INamedTypeSymbol contract in selected.OrderBy(static pair => pair.Key, StringComparer.Ordinal)
                         .Select(static pair => pair.Value))
                Emit(production, contract);
        });
    }

    private static bool IsMarked(INamedTypeSymbol type) => type.GetAttributes().Any(attribute =>
        attribute.AttributeClass?.ToDisplayString() == Marker);

    private static void Emit(SourceProductionContext context, INamedTypeSymbol contract)
    {
        string identity = contract.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string[] methods = contract.GetMembers().OfType<IMethodSymbol>()
            .Where(static method => method.MethodKind == MethodKind.Ordinary)
            .Select(method => CanonicalMethod(identity, method)).OrderBy(static method => method, StringComparer.Ordinal).ToArray();
        string[] channels = methods.Select(method => ChannelRow(method)).ToArray();
        string digest = Hash("hybridcpu.static-contract/v2|" + identity + "|" + string.Join("|", channels));
        string ns = contract.ContainingNamespace.IsGlobalNamespace ? "" : contract.ContainingNamespace.ToDisplayString();
        string typeName = "HybridCpuGeneratedContract_" + Sanitize(contract.Name) + "_" + digest.Substring(0, 12);
        var text = new StringBuilder();
        text.AppendLine("// <auto-generated/>");
        text.AppendLine("#nullable enable");
        if (ns.Length != 0) text.Append("namespace ").Append(ns).AppendLine(";");
        text.Append("internal static class ").Append(typeName).AppendLine();
        text.AppendLine("{");
        text.Append("    internal const string ContractIdentity = \"").Append(Escape(identity)).AppendLine("\";");
        text.Append("    internal const string ContractDigest = \"").Append(digest).AppendLine("\";");
        text.AppendLine("    internal static readonly string[] MethodIdentities = new string[]");
        text.AppendLine("    {");
        foreach (string method in methods)
            text.Append("        \"").Append(Escape(method)).AppendLine("\",");
        text.AppendLine("    };");
        text.AppendLine("    // Declaration metadata only: no serializer, dispatch, ownership or runtime authority.");
        text.AppendLine("    internal static readonly string[] ChannelManifestRows = new string[]");
        text.AppendLine("    {");
        foreach (string channel in channels)
            text.Append("        \"").Append(Escape(channel)).AppendLine("\",");
        text.AppendLine("    };");
        text.AppendLine("    internal static readonly ulong[] WireIds = new ulong[]");
        text.AppendLine("    {");
        foreach (string method in methods)
            text.Append("        0x").Append(WireId(method)).AppendLine("UL,");
        text.AppendLine("    };");
        text.AppendLine("}");
        context.AddSource(typeName + ".g.cs", text.ToString());
    }

    private static string CanonicalMethod(string owner, IMethodSymbol method) => owner + "::" + method.Name + "(" +
        string.Join(",", method.Parameters.Select(static parameter => parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))) +
        "):" + method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    private static string WireId(string method) => Hash("hybridcpu.static-channel-wire-id/v1|" + method).Substring(0, 16);
    private static string ChannelRow(string method) => WireId(method) + ":" + method +
        ":serializer=unqualified:deserializer=unqualified:dispatch=declaration-only:ownership=unqualified";
    private static string Sanitize(string value) => new(value.Select(static character =>
        char.IsLetterOrDigit(character) ? character : '_').ToArray());
    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    private static string Hash(string value)
    {
        using (var algorithm = SHA256.Create())
            return BitConverter.ToString(algorithm.ComputeHash(Encoding.UTF8.GetBytes(value))).Replace("-", "").ToLowerInvariant();
    }
}
