<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>HybridCPU.Compiler.Llvm</AssemblyName>
    <RootNamespace>HybridCPU.Compiler.Llvm</RootNamespace>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LLVMSharp" Version="20.1.2" />
    <PackageReference Include="LLVMSharp.Interop" Version="20.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\HybridCPU.Compiler.Core.csproj"
                      GlobalPropertiesToRemove="DefineTestSupport;BuildRuntimeDiagnosticConsole;HybridCpuIseProjectReferenceProperties" />
  </ItemGroup>

</Project>
