namespace YAKSys_Hybrid_CPU.Core.Pipeline
{
    // Canonical pipeline events consumed by the pipeline FSM.

    /// <summary>
    /// A structural change to pipeline state.
    ///
    /// Distinct from <c>InternalOp</c>: it does not produce a register result.
    /// VMX transitions are intentionally absent here and retire through the typed
    /// VMX retire/outcome plane instead of a compatibility event mirror.
    /// </summary>
    public abstract record PipelineEvent
    {
        /// <summary>VT that generated this event.</summary>
        public required byte VtId { get; init; }

        /// <summary>Bundle serial at the time this event was generated.</summary>
        public required ulong BundleSerial { get; init; }
    }

    // Trap events

    /// <summary>ECALL instruction - environment call from user, supervisor, or machine mode.</summary>
    public sealed record EcallEvent : PipelineEvent
    {
        /// <summary>System-call number captured from register a7 (x17).</summary>
        public required long EcallCode { get; init; }
    }

    /// <summary>EBREAK instruction - debug breakpoint trap.</summary>
    public sealed record EbreakEvent : PipelineEvent;

    /// <summary>
    /// Trap-entry pipeline event.
    /// Emitted when the CPU determines that a synchronous or asynchronous trap
    /// must be taken. Drives <c>Task -> TrapPending</c> in the pipeline FSM.
    /// </summary>
    public sealed record TrapEntryEvent : PipelineEvent
    {
        /// <summary>
        /// Exception or interrupt cause code using the RISC-V <c>mcause</c> convention.
        /// Bit 63 set means interrupt; bits 62:0 hold the cause number.
        /// </summary>
        public required ulong CauseCode { get; init; }

        /// <summary>
        /// Faulting virtual address (<c>mtval</c> or <c>stval</c>).
        /// Zero for non-address traps such as illegal instruction.
        /// </summary>
        public ulong FaultAddress { get; init; }
    }

    // Privilege-return events

    /// <summary>
    /// MRET instruction - return from machine-mode trap handler.
    /// Drives <c>TrapPending -> Task</c> in the pipeline FSM.
    /// </summary>
    public sealed record MretEvent : PipelineEvent;

    /// <summary>
    /// SRET instruction - return from supervisor-mode trap handler.
    /// Drives <c>TrapPending -> Task</c> in the pipeline FSM.
    /// </summary>
    public sealed record SretEvent : PipelineEvent;

    // Fence and ordering events

    /// <summary>
    /// FENCE or FENCE.I instruction.
    /// <see cref="IsInstructionFence"/> distinguishes the two variants:
    /// <see langword="false"/> = FENCE,
    /// <see langword="true"/> = FENCE.I.
    /// </summary>
    public sealed record FenceEvent : PipelineEvent
    {
        /// <summary><see langword="true"/> for FENCE.I; <see langword="false"/> for FENCE.</summary>
        public required bool IsInstructionFence { get; init; }
    }

    /// <summary>
    /// Memory-ordering event generated by atomic instructions carrying
    /// acquire and/or release ordering flags.
    /// </summary>
    public sealed record MemoryOrderingEvent : PipelineEvent
    {
        /// <summary>
        /// <see langword="true"/> if the issuing instruction has acquire ordering.
        /// </summary>
        public required bool IsAcquire { get; init; }

        /// <summary>
        /// <see langword="true"/> if the issuing instruction has release ordering.
        /// </summary>
        public required bool IsRelease { get; init; }
    }

    // Power and wait events

    /// <summary>WFI instruction - wait-for-interrupt low-power stall.</summary>
    public sealed record WfiEvent : PipelineEvent;

    // SMT and VT events

    /// <summary>YIELD instruction - cooperative VT thread yield.</summary>
    public sealed record YieldEvent : PipelineEvent;

    /// <summary>
    /// WFE instruction - wait-for-event stall.
    /// Drives the VT into <see cref="PipelineState.WaitForEvent"/>.
    /// </summary>
    public sealed record WfeEvent : PipelineEvent;

    /// <summary>
    /// SEV instruction - wake event for WFE-stalled VTs.
    /// Drives <see cref="PipelineState.WaitForEvent"/> back to <see cref="PipelineState.Task"/>.
    /// </summary>
    public sealed record SevEvent : PipelineEvent;

    /// <summary>
    /// POD_BARRIER instruction - pod-level synchronisation barrier.
    /// Consumed as a first-class pipeline event.
    /// </summary>
    public sealed record PodBarrierEvent : PipelineEvent;

    /// <summary>
    /// VT_BARRIER instruction - VT-level synchronisation barrier.
    /// Consumed without an FSM state change.
    /// </summary>
    public sealed record VtBarrierEvent : PipelineEvent;

    // FSM control events

    /// <summary>Hard reset of the pipeline FSM.</summary>
    public sealed record ResetEvent : PipelineEvent;

    /// <summary>Pipeline halt - all VTs have entered WFI or an irrecoverable state.</summary>
    public sealed record HaltEvent : PipelineEvent
    {
        /// <summary>Human-readable reason for the halt.</summary>
        public required string Reason { get; init; }
    }

    // Cluster synchronisation events

    /// <summary>
    /// POD_BARRIER executed: the VT enters the cluster synchronisation wait.
    /// Transitions <c>Task -> WaitForClusterSync</c>.
    /// </summary>
    public sealed record ClusterSyncEnterEvent : PipelineEvent
    {
        /// <summary>Affinity mask of cores participating in this barrier.</summary>
        public required ushort AffinityMask { get; init; }
    }

    /// <summary>
    /// All cores in the pod affinity mask reached the barrier.
    /// Transitions <c>WaitForClusterSync -> Task</c>.
    /// </summary>
    public sealed record ClusterSyncExitEvent : PipelineEvent;

    // Hardware PTW stall events

    /// <summary>
    /// TLB miss detected: a hardware PTW walk started and the pipeline stalls.
    /// Transitions <c>Task -> PtwStall</c>.
    /// </summary>
    public sealed record PtwWalkStartEvent : PipelineEvent
    {
        /// <summary>Virtual address that triggered the TLB miss.</summary>
        public required ulong FaultAddress { get; init; }
    }

    /// <summary>
    /// Hardware PTW completed successfully: the TLB is filled and the memory access may replay.
    /// Transitions <c>PtwStall -> Task</c>.
    /// </summary>
    public sealed record PtwWalkCompleteEvent : PipelineEvent
    {
        /// <summary>Physical address resolved by the page-table walker.</summary>
        public required ulong PhysicalAddress { get; init; }
    }

    /// <summary>
    /// Hardware PTW completed with a page fault.
    /// Transitions <c>PtwStall -> Task</c>; fault delivery is handled by the trap mechanism.
    /// </summary>
    public sealed record PtwWalkFaultEvent : PipelineEvent
    {
        /// <summary>Virtual address that caused the page fault.</summary>
        public required ulong FaultAddress { get; init; }

        /// <summary><see langword="true"/> if the fault came from a write access.</summary>
        public required bool IsWrite { get; init; }
    }

    // FSP clock-gating events

    /// <summary>
    /// FspPowerController gates this VT's fetch and decode stages after idle donor detection.
    /// Transitions <c>Task -> ClockGatedDonor</c>.
    /// </summary>
    public sealed record ClockGatedDonorEnterEvent : PipelineEvent;

    /// <summary>
    /// FspPowerController ungates this VT after new work or an interrupt arrives.
    /// Transitions <c>ClockGatedDonor -> Task</c>.
    /// </summary>
    public sealed record ClockGatedDonorExitEvent : PipelineEvent;

    // Scheduling backpressure events

    /// <summary>
    /// Scheduling backpressure event raised when a hardware resource becomes
    /// a structural bottleneck that prevents further micro-op issue.
    /// </summary>
    public sealed record BackpressureEvent : PipelineEvent
    {
        /// <summary>
        /// 128-bit mask of overloaded resources in <see cref="ResourceBitset"/> layout.
        /// Populated from <c>IHardwareOccupancyInput.GetHardwareOccupancyMask128()</c>.
        /// </summary>
        public required SafetyMask128 OverloadedResources { get; init; }

        /// <summary>
        /// Number of issue slots suppressed in this cycle due to backpressure.
        /// Used for telemetry and IPC accounting.
        /// </summary>
        public int SuppressedSlotCount { get; init; }
    }
}
