namespace YAKSys_Hybrid_CPU.Core.Pipeline
{
    // ─────────────────────────────────────────────────────────────────────────
    // IPipelineEventQueue — event delivery contract (V5 Phase 1)
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Receives <see cref="PipelineEvent"/> instances generated by execution units.
    ///
    /// The consumer is the pipeline FSM, which inspects each event and drives
    /// the appropriate state transition.  In Phase 1 the FSM consumer is a
    /// pass-through (<see cref="NullPipelineEventQueue"/>); full FSM wiring is
    /// Phase 3–4 scope.
    /// </summary>
    public interface IPipelineEventQueue
    {
        /// <summary>Deliver a <see cref="PipelineEvent"/> to the pipeline FSM.</summary>
        void Enqueue(PipelineEvent evt);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // NullPipelineEventQueue — Phase 1 passthrough consumer
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// No-op implementation of <see cref="IPipelineEventQueue"/>.
    ///
    /// Accepts events but takes no action.  Used until the pipeline FSM
    /// consumer is wired in Phase 3–4.
    /// </summary>
    public sealed class NullPipelineEventQueue : IPipelineEventQueue
    {
        /// <summary>Singleton instance.</summary>
        public static readonly NullPipelineEventQueue Instance = new();

        private NullPipelineEventQueue() { }

        /// <inheritdoc/>
        public void Enqueue(PipelineEvent evt) { }
    }
}
