<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>HybridCPU.Compiler.NativeAot.Adapter</AssemblyName>
    <RootNamespace>HybridCPU.Compiler.NativeAot</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cil\HybridCPU.Compiler.Cil.csproj" />
    <ProjectReference Include="..\Core\HybridCPU.Compiler.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Samples\**\*.cs" />
    <EmbeddedResource Remove="Samples\**\*" />
    <None Remove="Samples\**\*" />
  </ItemGroup>
</Project>
