namespace HybridCPU_ISE.Tests.Architecture;
public sealed class Rf1144CoreTableLifecycleImplementationTests
{
 [Fact] public void StaticTableStartsWithoutConfiguredAbsentSlots(){string p=Read("HybridCPU_ISE","NonRTL","Processor","Core","Processor.cs");Assert.Contains("public static CPU_Core[] CPU_Cores { get; private set; } = Array.Empty<CPU_Core>();",p);Assert.DoesNotContain("CPU_Cores = new CPU_Core[1024]",p);}
 [Fact] public void BootstrapPopulatesThenValidatesEverySlot(){string o=Read("HybridCPU_ISE","Legacy","Obsolete","Processor.Initialization.Obsolete.cs");Order(o,"BeginCoreTableConstruction(1024);","ReplaceCore(coreIndex, new CPU_Core((ushort)coreIndex, MainMemory));","ValidateCoreTableConstructionComplete();","InitializePodTopology();");}
 [Fact] public void CompletionFailsClosedOnFirstAbsentSlot(){string i=Read("HybridCPU_ISE","NonRTL","Processor","Core","Processor.CoreIdentity.cs");Order(i,"private static void ValidateCoreTableConstructionComplete()","for (int coreId = 0; coreId < cores.Length; coreId++)","_ = cores[coreId].Runtime;","contains an absent core slot at index {coreId}");Assert.Contains("_ = replacement.Runtime;",i);}
 [Fact] public void EvidenceKeepsTestMutationForNextSlice(){string e=Read("Documentation", "ArchitectureAuthorityRefactor","Evidence","RF11","rf11.44-core-table-lifecycle-implementation.md");string l=Read("Documentation", "ArchitectureAuthorityRefactor","10_RF11","00_CURRENT_STATUS_AND_LEDGER.md");Assert.Contains("direct test-table assignments remain",e,StringComparison.OrdinalIgnoreCase);Assert.Contains("--minimal-logs",e);Assert.Contains("RF-11.45",l);}
 static void Order(string s,params string[] m){int p=-1;foreach(string x in m){int n=s.IndexOf(x,p+1,StringComparison.Ordinal);Assert.True(n>p,x);p=n;}}static string Read(params string[] p)=>File.ReadAllText(p.Aggregate(Root(),Path.Combine));static string Root(){string? c=AppContext.BaseDirectory;while(c!=null){if(File.Exists(Path.Combine(c,"HybridCPU v2.slnx")))return c;c=Directory.GetParent(c)?.FullName;}throw new DirectoryNotFoundException();}
}
