using System.Text.RegularExpressions;
namespace HybridCPU_ISE.Tests.Architecture;
public sealed class Rf1145TestCoreTableMutationAdapterMigrationTests
{
 [Fact] public void TestSourcesHaveNoDirectTableAssignment(){string tests=Sources(Path.Combine(Root(),"HybridCPU_ISE.Tests"));Assert.Empty(Regex.Matches(tests,@"Processor\.CPU_Cores\s*="));Assert.Equal(6,Regex.Matches(tests,@"Processor\.EnsureCoreTableForTesting\(").Count);Assert.Equal(2,Regex.Matches(tests,@"Processor\.InstallCoreTableForTesting\(").Count);Assert.Equal(2,Regex.Matches(tests,@"Processor\.RestoreCoreTableForTesting\(").Count);}
 [Fact] public void TestAdaptersValidateOrConstructRuntimeIdentity(){string i=Read("HybridCPU_ISE","NonRTL","Processor","Core","Processor.CoreIdentity.cs");Assert.Contains("internal static void EnsureCoreTableForTesting",i);Assert.Contains("replacement[coreId] = new CPU_Core((ushort)coreId);",i);Assert.Contains("internal static CPU_Core[] InstallCoreTableForTesting",i);Assert.Contains("foreach (CPU_Core core in replacement)",i);Assert.Contains("_ = core.Runtime;",i);}
 [Fact] public void ProductionTableSetterIsNotPublic(){string p=Read("HybridCPU_ISE","NonRTL","Processor","Core","Processor.cs");Assert.Contains("CPU_Cores { get; private set; }",p);string prod=Sources(Path.Combine(Root(),"HybridCPU_ISE"));Assert.Equal(4,Regex.Matches(prod,@"CPU_Cores\s*=").Count);}
 [Fact] public void EvidenceClosesOnlyTestMutation(){string e=Read("Documentation", "Documentation", "ArchitectureAuthorityRefactor","Evidence","RF11","rf11.45-test-core-table-mutation-adapter-migration.md");string l=Read("Documentation", "Documentation", "ArchitectureAuthorityRefactor","10_RF11","00_CURRENT_STATUS_AND_LEDGER.md");Assert.Contains("production lifecycle is unchanged",e,StringComparison.OrdinalIgnoreCase);Assert.Contains("TestAssemblerConsoleApps was not run",e);Assert.Contains("RF-11.46",l);}
 static string Sources(string p)=>string.Join('\n',Directory.GetFiles(p,"*.cs",SearchOption.AllDirectories).Where(f=>!f.Contains("\\bin\\")&&!f.Contains("\\obj\\")).Select(File.ReadAllText));static string Read(params string[] p)=>File.ReadAllText(p.Aggregate(Root(),Path.Combine));static string Root(){string? c=AppContext.BaseDirectory;while(c!=null){if(File.Exists(Path.Combine(c,"HybridCPU v2.slnx")))return c;c=Directory.GetParent(c)?.FullName;}throw new DirectoryNotFoundException();}
}
