using System.Text.RegularExpressions;
namespace HybridCPU_ISE.Tests.Architecture;
public sealed class Rf1147ReferenceFacadeReadinessReauditTests
{
 [Fact] public void DeclarationAndSignatureSurfaceIsRecounted(){string root=Root();string p=Sources(Path.Combine(root,"HybridCPU_ISE"));Assert.Empty(Regex.Matches(p,@"partial\s+struct\s+CPU_Core"));Assert.Equal(67,Regex.Matches(p,@"partial\s+class\s+CPU_Core").Count);Assert.Equal(289,Regex.Matches(p,@"\b(?:ref|in|out)\s+(?:Processor\.)?CPU_Core\b").Count);Assert.Equal(40,Files(Path.Combine(root,"HybridCPU_ISE")).Count(f=>Regex.IsMatch(File.ReadAllText(f),@"\b(?:ref|in|out)\s+(?:Processor\.)?CPU_Core\b")));}
 [Fact] public void ClosedBlockersRemainClosed(){string root=Root();string p=Sources(Path.Combine(root,"HybridCPU_ISE"));string t=Sources(Path.Combine(root,"HybridCPU_ISE.Tests"));Assert.Empty(Regex.Matches(p,@"\bref\s+this(?:\s*[,\)]|\.)"));Assert.Empty(Regex.Matches(t,@"Processor\.CPU_Cores\s*="));Assert.DoesNotContain("Processor.CPU_Core core = "+"default;",t);Assert.Contains("CPU_Cores { get; private set; }",p);}
 [Fact] public void StructOnlyModifiersAreClosed(){string root=Root();string r=Read(root,"HybridCPU_ISE","CloseToHSL","Core","State","CPU_Core.RuntimeState.cs");string m=Read(root,"HybridCPU_ISE","CloseToHSL","Core","Pipeline","Retire","Evidence","CPU_Core.MatrixTileRetireState.cs");Assert.DoesNotContain("private readonly ref",r);Assert.Contains("internal bool OwnsMatrixTileReplayJournal",m);Assert.DoesNotContain("internal readonly bool OwnsMatrixTileReplayJournal",m);}
 [Fact] public void EvidenceAuthorizesOnlyNextModifierSlice(){string root=Root();string e=Read(root,"Documentation", "Documentation", "ArchitectureAuthorityRefactor","Evidence","RF11","rf11.47-reference-facade-readiness-reaudit.md");string l=Read(root,"Documentation", "Documentation", "ArchitectureAuthorityRefactor","10_RF11","00_CURRENT_STATUS_AND_LEDGER.md");Assert.Contains("no production code",e,StringComparison.OrdinalIgnoreCase);Assert.Contains("TestAssemblerConsoleApps was not run",e);Assert.Contains("RF-11.48",l);}
 static IEnumerable<string> Files(string p)=>Directory.GetFiles(p,"*.cs",SearchOption.AllDirectories).Where(f=>!f.Contains("\\bin\\")&&!f.Contains("\\obj\\"));static string Sources(string p)=>string.Join('\n',Files(p).Select(File.ReadAllText));static string Read(string r,params string[] p)=>File.ReadAllText(p.Aggregate(r,Path.Combine));static string Root(){string? c=AppContext.BaseDirectory;while(c!=null){if(File.Exists(Path.Combine(c,"HybridCPU v2.slnx")))return c;c=Directory.GetParent(c)?.FullName;}throw new DirectoryNotFoundException();}
}
