<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsTestProject>false</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Documentation\Stream WhiteBook\StreamEngine DmaStreamCompute\**" />
	  <EmbeddedResource Remove="Documentation\Stream WhiteBook\StreamEngine DmaStreamCompute\**" />
	  <None Remove="Documentation\Stream WhiteBook\StreamEngine DmaStreamCompute\**" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Documentation\Manuals\" />
	  <Folder Include="Documentation\Virtualization WhiteBook\" />
	  <Folder Include="Documentation\SecureCompute WhiteBook\" />
	</ItemGroup>

</Project>
